companyName: City11
keywords: City, evangelical, church, Leeds, best, christian, Jesus, bible, gospel, Christ, God, Faith, Lord
description: A Eleventy theme &amp; Sass Boilerplate
author: woodcock3
source_link: https://github.com/woodcock3/city11
favicon: /assets/img/favicon/favicon.ico
favicon_16: /assets/img/favicon/favicon-16x16.png
favicon_32: /assets/img/favicon/favicon-32x32.png
touch_icon: /assets/img/favicon/apple-touch-icon.png
safari_pinned_tab: /assets/img/favicon/safari-pinned-tab.svg

typewriter:
  - text
    message: Welcome
  - text
    message: Sundays: 10:45am and 6:30pm
  - text
    message: A city church with a community presence.
  - text
    message: We believe Jesus is good news.

counter_web_analytics: rusticola
netlify: true

colors:
  ckyellow: #febd2e
  ckblue: #01a8ff
  cityorange: #f19426
  cityblue: #259cd3
  citygreen: #06892f
